server:
  port: 8089

spring:
  application:
    name: CART-SERVICE

# Below conf is for overriding default eureka server setting by default eureka server connects to 8761 port
eureka:
  registerWithEureka: true
  fetchRegistry: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/

management:
  endpoints:
    web:
      exposure:
        include: mappings