spring:
  application:
    name: CUSTOMER-SERVICE

# Below conf is for overriding default eureka server setting by default eureka server connects to 8761 port
eureka:
  registerWithEureka: true
  fetchRegistry: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/